### ISSUE TITLE
Is fastcomposer good at generalizing concepts in images?

### ISSUE THREAD

**Issue by TruthSearcher** [mit-han-lab/fastcomposer#4]
I checked the examples:
![shryhrt](https://github.com/mit-han-lab/fastcomposer/assets/134135767/a930b368-8b51-47fc-a9b0-dece3aba7bf5)

It seems to retain the same photorealistic style as that input image and the same facial expression.

**Comment by tianweiy** [comment]
Thank you for the questions! 

1. Changing the facial expression is indeed hard. I think this is due to our training where we utilize crops from the original image as conditioning. Retrieval-based training may improve it and test-time conditioning on multiple reference images will also help. We will add this discussion to the paper later. 

2. I think currently stylization works quite well. It is essentially a tradeoff between identity preservation and prompt consistency. If we want to push for style consistency, we can lower the alpha, and get a more stylized image with some loss in identity preservation.
<img width="1276" alt="image" src="https://github.com/mit-han-lab/fastcomposer/assets/38497390/e8e89657-66ec-4cb3-babe-0d23acc707b0">
